### ISSUE TITLE
borked on xenial?

### ISSUE THREAD

**Issue by sokoow** [Bashfuscator/Bashfuscator#19]
```$ bashfuscator
Traceback (most recent call last):
  File "/usr/local/bin/bashfuscator", line 4, in <module>
    __import__('pkg_resources').run_script('bashfuscator==0.0.1', 'bashfuscator')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    code = compile(source, script_filename, 'exec')
  File "/usr/local/lib/python3.5/dist-packages/bashfuscator-0.0.1-py3.5.egg/EGG-INFO/scripts/bashfuscator", line 24
    raise ArgumentTypeError(f"{ivalue} is an invalid positive int value")
```

**Comment by capnspacehook** [comment]
Looks like you're using Python 3.5, as stated in the README, Bashfuscator requires Python 3.6 or above. Use Python 3.6 to install/run Bashfuscator and you shouldn't have any problems 👍

**Comment by capnspacehook** [comment]
Did that work @sokoow?

**Comment by sokoow** [comment]
Yep, on bionic it definitely works,, confirmed - it must have new nodejs version. On xenial/mint-xenial boxes I'm getting this:

```neo-node $ bashfuscator 
Traceback (most recent call last):
  File "/home/sokoow/.local/bin/bashfuscator", line 4, in <module>
    __import__('pkg_resources').run_script('bashfuscator==0.0.1', 'bashfuscator')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    code = compile(source, script_filename, 'exec')
  File "/usr/local/lib/python3.5/dist-packages/bashfuscator-0.0.1-py3.5.egg/EGG-INFO/scripts/bashfuscator", line 24
    raise ArgumentTypeError(f"{ivalue} is an invalid positive int value")
                                                                       ^
SyntaxError: invalid syntax
neo-node ~ $ node -v
v4.2.6
```
